
var config = {
    "AppName": "Airstack.app",
    "AppTitle": "Airstack App Title",
    "AppDesc": "Make your own niche directory or categorized resources collection with React, Airtable and Bootstrap",
    "AppCopyright": "&copy;2018 Airstack",
    "AppLogo": "",
    "AppIcon": "",
    "AppImage": "",
    "Layout": "Layout1",
    "ContainNavbar": true,
    "ContainFooter": true,
    "ShowNavBrand": false,
    "ShowNavLogo": true,
    "LblResource": "Resource",
    "LblResources": "Resources",
    "LblCategory": "Category",
    "LblCategories": "Categories",
    "LblFeatured": "Featured",
    "LblSuggest": "Suggest",
    "LblSuggestHeading": "Submit a Resource",
    "LblSuggestSubHeading": "",
    "LblView":"View",
    "LblShowMore":"Show More",
    "HomeLayout":"Home",
    "HomeHeading":"Welcome to Airstack",
    "HomeSubHeading":"It's time to React with Airtable!",
    "EnableDirectLinks": false,
    "HtmlModalThanks": `<h3>Thank you!</h3><p className="lead">Your submission was successful. Check your email for further correspondence from us.</p><button className="btn btn-outline-primary" data-dismiss="modal">OK</button>`,
    "SocialTwitter": "@ThemesGuide",
    "SocialGitHub": "ThemesGuide",
};

export default config;